Wildfly Features
================
:author: Stuart Douglas
:email: <stuart.w.douglas@gmail.com>
///////////////////////
	Themes that you can choose includes:
	web-2.0, swiss, neon beamer
///////////////////////
:deckjs_theme: swiss2
///////////////////////
	Transitions that you can choose includes:
	fade, horizontal-slide, vertical-slide
///////////////////////
:deckjs_transition: horizontal-slide
///////////////////////
	AsciiDoc use `source-highlight` as default highlighter.

	Styles available for pygment highlighter:
	monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
	tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

	Uncomment following two lines if you want to highlight your code
	with `Pygments`.
///////////////////////
:pygments:
:pygments_style: default
///////////////////////
	Uncomment following line if you want to scroll inside slides
	with {down,up} arrow keys.
///////////////////////
//:scrollable:
///////////////////////
	Uncomment following line if you want to link css and js file
	from outside instead of embedding them into the output file.
///////////////////////
//:linkcss:
///////////////////////
	Uncomment following line if you want to count each incremental
	bullet as a new slide
///////////////////////
//:count_nested:
:customcss: slides.css

== Current State
 * Wildfly has now been split into two repositories, core and full
 * Build is now done using a custom maven plugin rather than some ant scripts
 * Build now incorporates 'Feature Packs', which are basically a set of instructions for building a Wildfly instance

== Feature packs
 * The build is broken up into three feature packs
 Core:: The core Wildfly management functionality, not really usable by itself
 Web:: Core + Undertow + Naming
 Full:: Everything else

== Feature packs TODO
 * Integration/replacement for patching
 * Dynamic feature installation (i.e. a yum like interface to add features)
 * Docker integration?
 * Cross product concerns
 * How much of this do we want to support in EAP vs leaving as community only
 * How does this integrate with the installer?


