Wildfly and SSL
===============
:author: Stuart Douglas
:email: <stuart.w.douglas@gmail.com>
///////////////////////
	Themes that you can choose includes:
	web-2.0, swiss, neon beamer
///////////////////////
:deckjs_theme: swiss2
///////////////////////
	Transitions that you can choose includes:
	fade, horizontal-slide, vertical-slide
///////////////////////
:deckjs_transition: horizontal-slide
///////////////////////
	AsciiDoc use `source-highlight` as default highlighter.

	Styles available for pygment highlighter:
	monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
	tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

	Uncomment following two lines if you want to highlight your code
	with `Pygments`.
///////////////////////
:pygments:
:pygments_style: default
///////////////////////
	Uncomment following line if you want to scroll inside slides
	with {down,up} arrow keys.
///////////////////////
//:scrollable:
///////////////////////
	Uncomment following line if you want to link css and js file
	from outside instead of embedding them into the output file.
///////////////////////
//:linkcss:
///////////////////////
	Uncomment following line if you want to count each incremental
	bullet as a new slide
///////////////////////
//:count_nested:
:customcss: slides.css

== Wildfly and SSL
 * This session is a discussion about SSL and Wildfly

== Current Issues
 * JSSE Performance is not on par with OpenSSL
 * Does not support ALPN without hacking stuff into the boot path

== ALPN - Current State
 * Current support is provided by a Jetty maintained jar that must be placed on the boot class path
 * A specific version is needed to match the JVM version
 * Will be supported in JDK 9, but API is not finalised
 * Possibly backported via a proprietary API to JDK 8

== Performance - Current State
 * JSSE performance has improved in JDK8, but is significantly slower than OpenSSL
 * JDK9 should improve performance further, but there are no guarentees it will catch up to OpenSSL

== Proposed solution
 * Create a new project based on the TCNative code base to provide SSLContext support via OpenSSL
 * No Undertow or other dependencies, this will be a standalone project
 * As much as practical JSSE API's will be used, so it should be a drop in replacement for JSSE
 * Use dlopen to allow the same binary to be used against different OpenSSL versions
 * Eventually (hopefully) this will no longer be nessesary as JSSE catches up

== Current state
 * Prototype has been done, and (mostly) passes the Undertow test suite
 * https://github.com/stuartwdouglas/ssl-experiments
 * Needs a name (and TAG approval?)
 * Needs more work, and extensive testing on multiple platforms


